### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by sammcj** [Andargor/edce-client#15]
```
% python3 client-setup.py
Enter your Frontier Store credentials here. You can leave your username or password empty, however you will be prompted every time you run the edce_client.py script.
Frontier Store Username: 
Frontier Store Password:
Send market data to EDDN. No private information is sent. [Y/n]:
Setup complete. edce.ini written.
**NOTE: Your username and password are not stored encrypted. Make sure this file is protected.

% python3 edce_client.py
Traceback (most recent call last):
  File "edce_client.py", line 7, in <module>
    import edce.query
  File "/Users/samm/git/edce-client/edce/query.py", line 7, in <module>
    import requests
ImportError: No module named 'requests'
```

Python 3.4.3

**Comment by sammcj** [comment]
OK looks like the app requires the python3 library `requests` but doesn't specify it.

```
% pip3 install requests
Collecting requests
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 654kB/s
Installing collected packages: requests
Successfully installed requests-2.7.0
samm-mb ~/git/edce-client % python3 edce_client.py

Verification Code required. You will receive an email from Frontier with a code in it. Enter it here:
```
